src/model/user.rs
=> Support property `group`  for badges

src/client.rs
- 🐛 The API URLs in fetch request were incorrect [#12]
=> API URLs in fetch request were incorrect

src/client.rs, src/model/server_stats.rs
- 🛠️ Updated the methods and models to conform to the new response struct of the Server Statistics [#16]
=> Update for new Server Statistics

src/client.rs, src/model/user.rs
- 🛠️ Updated the models and methods to conform to the new User Info endpoint [#19]
=> Conform to new User Info endpoint

src/client.rs, src/model/searched_user.rs
- 🛠️ Updated the method and models to conform to the new Search User endpoint [#21]
=> Conform to new User Search endpoint

src/client.rs, src/model/mod.rs, src/model/summary/forty_lines.rs, src/model/summary/mod.rs, src/model/summary/record.rs, src/model/user.rs
- ✨ Implemented `Client::get_user_40l` method [#23]
- 🛠️ Derived the traits `Eq`, `PartialEq`, `Hash` to the `UserId` struct [b900846043c2070513bc45d6258ffa3fd1bbccfa]
=> Implement method for 40 LINES endpoint

src/client.rs, src/model/summary/blitz.rs, src/model/summary/mod.rs
- ✨ Implement `Client::get_user_blitz` method [#25]
=> Implement method for BLITZ endpoint

src/client.rs, src/model/summary/mod.rs, src/model/summary/zenith.rs
- ✨ Implemented `Client::get_user_zenith` method [#27]
=> Implement method for QUICK PLAY endpoint

src/client.rs, src/model/summary/zenith.rs
- ✨ Implemented `Client::get_user_zenith_ex` method [#29]
=> Implement method for EXPERT QUICK PLAY endpoint

src/client.rs, src/model/summary/league.rs, src/model/summary/mod.rs
- ✨ Implemented `Client::get_user_league` method [#31]
=> Implement method for TETRA LEAGUE endpoint

src/client.rs, src/model/summary/mod.rs, src/model/summary/zen.rs
- ✨ Implemented `Client::get_user_zen` method [#33]
=> Implement method for ZEN endpoint

src/client.rs, src/model/summary/achievements.rs, src/model/summary/mod.rs
- ✨ Implemented `Client::get_user_achievements` method [#35]
=> Implement method for Archievements endpoint

src/client.rs, src/model/summary/mod.rs
- ✨ Implemented `Client::get_user_all_summaries` method [#37]
=> Implement method for "User Summary: All" endpoint

src/client.rs, src/model/leaderboard.rs, src/model/mod.rs
- ✨ Implemented `Client::get_leaderboard` method [#39]
=> Implement method for User Leaderboard endpoint

src/client.rs, src/model/mod.rs, src/model/records_leaderboard.rs
- ✨ Implemented `Client::get_records_leaderboard` method [#45]
=> Implement method for Records Leaderboard endpoint

src/client.rs, src/model/mod.rs, src/model/news.rs
- ✨ Implemented `Client::get_news_all` method [#49]
=> Implement method for "All Latest News" endpoint

src/client.rs, src/model/news.rs, tests/client.rs
- 🛠️  Updated and added method and models to conform to the new Latest News endpoint [#51]
=> Conform to new Latest News endpoint

src/client.rs, src/model/labs/mod.rs, src/model/labs/scoreflow.rs, src/model/mod.rs
- ✨ Implemented `Client::get_labs_scoreflow` method [#53]
=> Implement method for Labs Scoreflow endpoint

src/client.rs, src/model/labs/leagueflow.rs, src/model/labs/mod.rs
- ✨ Implemented `Client::get_labs_leagueflow` method [#55]
=> Implement method for Labs Leagueflow endpoint

src/client.rs, src/model/labs/league_ranks.rs, src/model/labs/mod.rs
- ✨ Implemented `Client::get_labs_league_ranks` method [#57]
=> Implement method for Labs League Ranks endpoint

src/client.rs, src/model/achievement_info.rs, src/model/mod.rs, src/model/summary/achievements.rs
- ✨ Implemented `Client::get_achievement_info` method [#59]
- 🛠️ The `Achievement::order` field is now optional [9c76219b8020b4c278cde102a79ec21083479944]
=> Implement method for Achievement Info endpoint

src/model/achievement_info.rs, src/model/cache.rs, src/model/leaderboard.rs, src/model/league_rank.rs, src/model/news.rs, src/model/role.rs, src/model/searched_user.rs, src/model/server_activity.rs, src/model/server_stats.rs, src/model/summary/league.rs, src/model/summary/record.rs, src/model/user.rs
- ✨ Implemented some useful methods for the models [#67]
=> Useful Methods for Models

src/client.rs, src/client/error.rs, src/constants.rs, src/model/achievement.rs, src/model/achievement_info.rs, src/model/cache.rs, src/model/labs/league_ranks.rs, src/model/labs/leagueflow.rs, src/model/labs/mod.rs, src/model/labs/scoreflow.rs, src/model/leaderboard.rs, src/model/league_rank.rs, src/model/mod.rs, src/model/news.rs, src/model/records_leaderboard.rs, src/model/role.rs, src/model/searched_user.rs, src/model/server_activity.rs, src/model/server_stats.rs, src/model/summary/achievements.rs, src/model/summary/blitz.rs, src/model/summary/forty_lines.rs, src/model/summary/league.rs, src/model/summary/mod.rs, src/model/summary/record.rs, src/model/summary/zen.rs, src/model/summary/zenith.rs, src/model/user.rs, src/model/user_records.rs, src/util.rs
- 📚 Improved the documentation [#69]
=> Docs Improvements

src/client.rs, src/client/param/record.rs, src/client/param/record_leaderboard.rs, src/client/param/user_leaderboard.rs, src/model/leaderboard.rs, src/model/news.rs, src/model/summary/record.rs, src/model/user.rs, src/util.rs
- 📚 Wrote "Panics" sections in some documentations [#77]
=> Write "Panics" sections in some docs

src/client.rs, src/client/param/record.rs, src/client/param/record_leaderboard.rs, src/client/param/user_leaderboard.rs, src/util.rs
- ♻️ Improved the panic handling [#79]
- ♻️ Replaced the panic calls with a new utility function for the limit validations [abe7ca50069fc3c5d00456f9c6de08c12fc3c5fc]
- ✨ Implemented a new utility function `validate_limit` [b40512e58e738bee183b51e7aade9958e6203770]
- ♻️ The `to_unix_ts` utility function now uses the `Result::expect` method instead of the `match` expression to handle the errors [da62c75a287bc765f917a8267d75f7dc5536c6ef]
=> Panic Handling Improvements

src/model/achievement_info.rs, src/model/leaderboard.rs, src/model/summary/record.rs, src/model/user.rs
- 🛠️ Made the optional boolean fields in the models completely boolean [#87]
=> Make optional boolean fields in models completely boolean

src/model/achievement_info.rs, src/model/leaderboard.rs, src/model/news.rs, src/model/summary/league.rs, src/model/summary/mod.rs, src/model/summary/record.rs
- ✏️ Renamed some models to appropriate names [#91]
=> Rename some models to appropriate names

src/model/achievement_info.rs, src/model/leaderboard.rs, src/model/macros/get_user.rs, src/model/macros/mod.rs, src/model/macros/role.rs, src/model/macros/some_at.rs, src/model/mod.rs, src/model/news.rs, src/model/searched_user.rs, src/model/summary/league.rs, src/model/summary/record.rs, src/model/user.rs, src/model/util/user_id.rs
- ♻️ Implement some methods of the models with macros [#95]
=> Implement macros for model methods

Cargo.toml, src/client.rs, src/client/error.rs
- ✨ Added support for `X-Session-ID` [#97]
- 🛠️ The `Client` struct is now reusable [ed10aef00d430c3fda8fb08ccb46d289f6701a55]
=> Add support for `X-Session-ID`

CHANGELOG.md
- 📚 Fixed an incorrect link in the `CHANGELOG.md`  [#103]
=> Fix incorrect link in `CHANGELOG.md`
